### ISSUE TITLE
报语法错误

### ISSUE THREAD

**Issue by yu4hao4** [gh0stkey/RGPerson#1]
![image](https://user-images.githubusercontent.com/46297861/63003946-e60ff000-beab-11e9-96d8-3c8c70c2149d.png)

**Comment by gh0stkey** [comment]
什么版本python3 我的是：Python 3.7.1rc2

**Comment by yu4hao4** [comment]
3.5.2

**Comment by gh0stkey** [comment]
建议切换3.7

**Comment by yu4hao4** [comment]
嗯嗯
