### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by lupus721** [gh0stkey/RGPerson#2]
比如是否考虑多加一个常用用户名密码，生成一次性邮箱，设置参数来确认生成那些字段还是全生成，输出到文档等功能

**Comment by gh0stkey** [comment]
那样涉及的东西就较多了，且很多功能需要联网无法离线，不符合我的设计初衷，并且生成哪些字段，我觉得有点多次一举，全生成，直接复制想要的不就OK了么～
