### ISSUE TITLE
报错，无法运行

### ISSUE THREAD

**Issue by tigerfans** [gh0stkey/RGPerson#6]
Traceback (most recent call last):
  File "C:\TEMP\RGPerson-master\RGPerson.py", line 139, in <module>
    print("ID: {}\n姓名: {} 拼音: {} \n年龄: {}\n性别: {}\n身份证: {}\n手机号: {} {}\n组织机构代码: {}\n统一社会信用代码: {}\n单位性质: {}".format(genHackerId(), name, ''.join(lazy_pinyin(name)), age, sex, genIdCard(age, gender), list(genMobile().keys())[0], list(genMobile().values())[0], genOrgCode(), list(genCreditCode().keys())[0], list(genCreditCode().values())[0]))
  File "C:\TEMP\RGPerson-master\RGPerson.py", line 130, in genHackerId
    ids = f.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 334: illegal multibyte sequence

**Comment by gh0stkey** [comment]
编码问题
